"""
game.html  →  sls/index.html
把网页版里那段空的记分接口，换成真的 xAPI（程式库 + wrapper）。
Swap the web build's empty scoring hook for the real xAPI (library + wrapper).

用法 ｜ Usage:  python3 tools/build-sls.py
改过 game.html 之后一定要重跑，否则两版会不一样。
Re-run after every edit to game.html, or the two builds drift apart.

为什么整个程式库得内嵌：SLS 把内容放进 sandbox iframe 执行，挡掉所有对外请求 ——
不能载 CDN，不能用外部 <script src>。所以 41KB 的程式库只能贴成纯文字。
Why the library is inlined: SLS runs uploaded content in a sandboxed iframe
that blocks every outbound request — no CDN, no external <script src>. So the
41KB library has to sit in the file as plain text.
"""
import os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bank

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src  = open(os.path.join(ROOT, "game.html"), encoding="utf-8").read()
lib  = open(os.path.join(ROOT, "tools", "xapiwrapper-1.11.0.min.js"), encoding="utf-8").read()

# 记分接口整段（含上面的中英注释）都换掉 ｜ replace the whole hook section, comments and all
HOOK = re.compile(r"/\* ═+\n   三、记分接口.*?SLS-HOOK-END ▲▲▲ \*/", re.S)
assert HOOK.search(src), "SLS-HOOK markers not found in game.html"

REAL = r'''/* ══════════════════════════════════════════════════════════════
   三、记分接口 ｜ 3. THE SCORING HOOK
   ▼▼▼ SLS-HOOK-START ▼▼▼   本档由 tools/build-sls.py 生成，请勿手改
   Generated by tools/build-sls.py — edit game.html instead, then rebuild.

   分数为什么曾经记录不到 SLS：
   SLS 的 xAPI 初始化，是从网址查询字符串读 endpoint / auth / agent / stateId /
   activityId。学生若另开分页，这些参数全部丢失，JSON.parse(agent) 抛出错误，
   而官方范例的 sendScore() 只在 catch 里 console.error —— 于是完全静默失败：
   游戏照常运作，学生做完，分数从未送出。
   Why scores silently failed before: SLS passes the launch parameters in the
   query string. Open the activity in a new tab and they are gone, JSON.parse
   throws, and the official sample only console.errors in its catch — so the
   game plays, the student finishes, and nothing is ever sent.

   对策：init() 回传成功与否，并且<b>记下缺了哪几个参数</b>。
   少了哪一个会写进顶栏那个小标的 tooltip，也印在 console 里 ——
   下次再出问题，不必猜。
   Fix: init() reports success and records WHICH parameters were missing. That
   list goes into the top-bar chip's tooltip and the console, so the next time
   something is wrong there is nothing to guess at.
   ══════════════════════════════════════════════════════════════ */
const XAPI = {
  p:null, inSLS:false, missing:[],
  /* 这一版是给 SLS 用的，所以「记不了分」确实是件该讲的事
     This build is for SLS, so a scoring failure genuinely is worth mentioning */
  everSLS:true,
  /* 页面是不是被嵌在框里。SLS 一定是嵌着跑的 ——
     所以「嵌着但没参数」跟「根本没嵌」是两回事，不能都当成另开分页。
     Whether we are inside a frame. SLS always embeds, so "framed but without
     parameters" and "not framed at all" are different situations and must not
     both be treated as a rogue new tab. */
  embedded:(function(){ try{ return window.self !== window.top; }catch(e){ return true; } })(),

  init(){
    const q = new URLSearchParams(location.search);
    const need = ['endpoint','auth','agent','stateId','activityId'];
    this.missing = need.filter(k => !q.get(k));
    if(this.missing.length){
      console.warn('[xAPI] 没有记分参数 ｜ no launch parameters. 缺 ｜ missing:',
                   this.missing.join(', '), '| embedded:', this.embedded);
      return false;
    }
    try{
      const agent = JSON.parse(q.get('agent'));
      if(!agent) throw new Error('agent parsed to null');
      ADL.XAPIWrapper.changeConfig({
        endpoint: q.get('endpoint') + '/',
        auth: 'Basic ' + q.get('auth')
      });
      this.p = {agent:agent, stateId:q.get('stateId'), activityId:q.get('activityId')};
      this.inSLS = true;
      console.log('[xAPI] 已连上 SLS ｜ connected, scores will be recorded');
      return true;
    }catch(e){
      this.missing = ['agent 解析失败 ｜ agent could not be parsed'];
      console.warn('[xAPI] init failed:', e);
      return false;
    }
  },

  /* 送出的必须是三关的<累计总分>，不能是单次得分。
     SLS 收的是 state 文件，后写覆盖前写 —— 若只送单关分数，
     学生日后补做第三关，就会把前两关的分数一起覆盖掉。
     Always send the RUNNING TOTAL. SLS stores this as a state document and a
     later write replaces the earlier one, so sending one level's score would
     wipe the others when a student returns days later to finish. */
  sendScore(score, max){
    try{
      if(!this.p) return;
      ADL.XAPIWrapper.sendState(this.p.activityId, this.p.agent, this.p.stateId, null,
        {score:score, maxScore:max, completed:true});
      console.log('[xAPI] 已送出 ｜ sent:', score + '/' + max);
    }catch(e){ console.warn('[xAPI] sendScore failed:', e); }
  }
};
/* ▲▲▲ SLS-HOOK-END ▲▲▲ */'''

out = HOOK.sub(lambda m: REAL, src, count=1)

# 程式库要排在 XAPI 之前载入，所以插在 <head> 里 ｜ the library must load first
tag = '<script>\n' + lib + '\n</script>\n'
i = out.index('</head>')
out = out[:i] + tag + out[i:]

out = out.replace(
    "这是「网页版」：没有 xAPI，分数只显示在画面上，不会送进 SLS。",
    "这是「SLS 版」：内嵌 xAPIWrapper，做完自动把分数送进教师后台。")
out = out.replace(
    "  SLS 版在 sls/index.html，内容一字不差，只多了记分程式码。",
    "  网页版在 game.html，内容一字不差，只少了记分程式码。")
out = out.replace(
    "  This is the WEB build: no xAPI, the score only ever shows on screen.\n"
    "  The SLS build is sls/index.html — identical content, plus the scoring code.",
    "  This is the SLS build: xAPIWrapper embedded, scores land in the gradebook.\n"
    "  The web build is game.html — identical content, minus the scoring code.")

dst = os.path.join(ROOT, "sls", "index.html")
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, "w", encoding="utf-8").write(out)

print(f"game.html      {len(src)/1024:7.1f} KB")
print(f"+ xAPIWrapper  {len(lib)/1024:7.1f} KB")
print(f"= sls/index.html {len(out)/1024:5.1f} KB")
levels, _, _ = bank.load()
mx = bank.total_max(levels)
print(f"\n题库：{len(levels)} 关 {sum(len(l['panels']) for l in levels)} 版面 {mx} 分")
print(f"上传 SLS 时把 Maximum Marks 设成 {mx} ｜ set Maximum Marks to {mx} on upload")
